name: "Misc"

on:
  pull_request:

jobs: 
  labeler: 
    permissions: 
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/labeler@v4
        with: 
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: GitHub CODEOWNERS Validator
        uses: mszostok/codeowners-validator@v0.7.4
        with:
          checks: "files,owners,duppatterns,syntax"
          experimental_checks: "notowned,avoid-shadowing"
          github_access_token: "${{ secrets.OWNERS_VALIDATOR_GITHUB_SECRET }}"
