name: "Misc"

on:
  push:
    branches:
      - master
  pull_request:

jobs: 
  labeler:
    name: PR Labeler
    permissions: 
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps: 
      - uses: actions/labeler@v4
        with: 
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  codeowners:
    name: CODEOWNERS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: GitHub CODEOWNERS Validator
        uses: mszostok/codeowners-validator@v0.7.4
        with:
          checks: "files,owners,duppatterns,syntax"
          experimental_checks: "notowned,avoid-shadowing"
          github_access_token: "${{ secrets.CODEOWNERS_VALIDATOR_GITHUB_SECRET }}"

  actionlint:
    name: Action Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.github_token }
          fail_on_error: true

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          fail_on_error: true

  yamllint:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          fail_on_error: true
