name: "Terraform"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform_mod:
    name: "Terraform Modifications"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Terraform modified"; exit 0

  terraform_fmt:
    name: "Terraform Format"
    runs-on: ubuntu-latest
    needs: terraform_mod
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

  terraform_validate:
    name: "Terraform Validate"
    runs-on: ubuntu-latest
    needs: terraform_mod
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup CI
        run: .github/workflows/resources/setupci.sh
        working-directory: .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

  terraform_plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    needs: terraform_validate
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup CI
        run: .github/workflows/resources/setupci.sh
        working-directory: .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true

  infracost:
    runs-on: ubuntu-latest
    name: Run Infracost
    needs: terraform_validate
    steps:
      - name: Checkout master
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Checkout code
        if: github.event_name == 'push'
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
        
      - name: Checkout previous commit
        if: github.event_name == 'push'
        run: git checkout HEAD~

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Comparison Infracost
        run: |
          infracost breakdown --path src/ \
                              --format json \
                              --out-file /tmp/infracost-master.json

      - name: Checkout new code
        uses: actions/checkout@v3

      - name: Infracost on commit
        if: github.event_name == 'push'
        run: |
          infracost diff --path src/ \
                         --compare-to /tmp/infracost-master.json

      - name: Infracost on PR branch
        if: github.event_name == 'pull_request'
        run: |
          infracost diff --path src/ \
                         --format json \
                         --compare-to /tmp/infracost-master.json \
                         --out-file /tmp/infracost.json

      - name: Exit on no Infra diff
        if: github.event_name == 'pull_request'
        run: echo "DIFF=$(jq -r '.projects[0].diff.resources | length' /tmp/infracost.json)" >> "$GITHUB_ENV"

      - name: Post Infracost comment
        if: ${{ env.DIFF != '0' && github.event_name == 'pull_request' }}
        run: |
          infracost comment github --path /tmp/infracost.json \
                                   --repo "$GITHUB_REPOSITORY" \
                                   --github-token "${{github.token}}" \
                                   --pull-request "${{github.event.pull_request.number}}" \
                                   --behavior update
