name: "Terraform"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup CI
        run: .github/workflows/resources/setupci.sh
        working-directory: .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true

  infracost:
    runs-on: ubuntu-latest
    name: Run Infracost
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Setup CI
        run: .github/workflows/resources/setupci.sh
        working-directory: .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Infracost on master
        run: >-
          infracost breakdown --path src/infra
                              --terraform-parse-hcl
                              --format json
                              --out-file /tmp/infracost-master.json

      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Infracost on PR branch
        run: >-
          infracost breakdown --path src/infra
                              --terraform-parse-hcl
                              --format json
                              --compare-to /tmp/infracost-master.json
                              --out-file /tmp/infracost.json

      - name: Post Infracost comment
        if: ${{ env.DIFF != '0' }}
        run: |
          infracost comment github --path /tmp/infracost.json \
                                   --repo $GITHUB_REPOSITORY \
                                   --github-token ${{github.token}} \
                                   --pull-request ${{github.event.pull_request.number}} \
                                   --behavior update
